# MkDocs configuration for PDF builds
# Usage: mkdocs build -f mkdocs-pdf.yml

INHERIT: mkdocs-base.yml

site_url: "https://docs.percona.com/percona-server/"

# Material theme features
theme:
  name: material
  logo: _images/postgresql-mark.svg
  favicon: _images/postgresql-fav.svg
  custom_dir: _resourcepdf/overrides/
  font:
    text: Roboto  
    code: Roboto Mono
  icon:
    edit: material/file-edit-outline
    view: material/file-eye-outline

nav:
  - Home: index.md
  - psmysql-pro.md
  - get-help.md
  - Release notes:
    - Release notes index: release-notes/release-notes-index.md
    - release-notes/8.4.3-3.md
    - release-notes/8.4.2-2.md
    - release-notes/8.4.1.md
    - release-notes/8.4.0-1.md
  - Features:
    - adaptive-network-buffers.md
    - Audit Log Filter:
      - audit-log-filter-overview.md
      - install-audit-log-filter.md
      - Formats: 
        - Overview: audit-log-filter-formats.md
        - XML (New style): audit-log-filter-new.md
        - XML (Old style): audit-log-filter-old.md
        - JSON: audit-log-filter-json.md
      - write-filter-definitions.md
      - audit-log-filter-security.md
      - audit-log-filter-compression-encryption.md
      - reading-audit-log-filter-files.md
      - manage-audit-log-filter.md
      - filter-audit-log-filter-files.md
      - audit-log-filter-restrictions.md
      - audit-log-filter-naming.md
      - disable-audit-log-filter.md
      - audit-log-filter-variables.md
      - uninstall-audit-log-filter.md
    - binlog-space.md
    - extended-select-into-outfile.md
    - fips.md
    - innodb-expanded-fast-index-creation.md
    - kill-idle-trx.md
    - percona-sequence-table.md
    - procfs-plugin.md
    - proxy-protocol-support.md
    - sequence-table.md
    - slowlog-rotation.md
    - threadpool.md
    - trigger-updates.md 
    - udf-percona-toolkit.md
    - utility-user.md
  - Quickstart:
    - Quickstart - Overview: quickstart-overview.md
    - Quickstart - Run and create database (containers): quickstart-docker.md
    - Quickstart - Install and create database (Ubuntu): quickstart-apt.md
    - Quickstart - Install and create database (Oracle Linux): quickstart-yum.md
    - Quickstart - Next steps: quickstart-next-steps.md
  - Install:
    - Install Percona Server for MySQL from repositories: installation.md
    - Before you start: 
      - download-instructions.md
    - Use APT:
      - Use APT repositories: apt-repo.md
      - Files in DEB package: apt-files.md
      - build-apt-packages.md
      - Downloaded DEB packages: apt-download-deb.md
      - Apt pinning: apt-pinning.md
      - Run Percona Server for MySQL: apt-run.md
      - Uninstall: apt-uninstall-server.md
    - Use YUM:
      - Use RPM repositories: yum-repo.md
      - Files in RPM package: yum-files.md
      - Downloaded RPM packages: yum-download-rpm.md
      - Run Percona Server for MySQL: yum-run.md
      - Uninstall: yum-uninstall.md
    - Use binary tarballs:
      - Install with binary tarballs: binary-tarball-install.md
      - Binary tarballs available: binary-tarball-names.md
    - Compile from source:
      - source-tarball.md
      - compile-percona-server.md  
    - Docker:
      - Install using Docker: docker.md
      - docker-config.md
    - Install Percona Server for MySQL Pro:
      - install-pro.md
      - pro-files.md
  - Upgrade:
    - upgrade.md
    - upgrade-strategies.md
    - upgrade-components.md
    - upgrade-percona-repos.md
    - upgrade-standalone-packages.md
    - upgrade-pro.md
    - downgrade.md
    - downgrade-from-pro.md
  - Post-Installation:
    - binlogging-replication-improvements.md
    - post-installation.md
    - AppArmor:
      - apparmor.md
      - apparmor-profiles.md
      - manage-apparmor-profiles.md
      - disable-apparmor.md
      - configure-apparmor.md
      - troubleshoot-apparmor.md
    - SELinux:
      - selinux.md
      - selinux-contexts.md
      - manage-selinux-modes.md
      - additional-selinux-tools.md
      - troubleshoot-selinux.md
  - Develop:
    - Fundamental SQL operations:
      - sql-basics.md
      - common-sql.md
      - select.md
      - insert.md
      - update.md
      - delete.md
      - sql-operators.md 
    - Advanced SQL features:
      - data-types-basic.md
      - functions.md
      - sql-conventions.md
      - sql-errors.md
      - sql-syntax.md
      - stored-procedures.md
      - stored-procedure-error-handling.md
      - stored-procedure-variables.md
      - triggers.md
      - troubleshooting-sql.md
    - JSON:
      - json-overview.md
  - Manage:
    - Database management:
        - database.md
        - table.md
        - create-table.md
        - modify-tables.md
        - isolation-levels.md
        - transaction-mgmt.md
        - views.md
        - authentication-methods.md
    - extended-show-grants.md
    - restrict-dynamic-log-locations.md
    - clone-plugin.md
    - Manage components:
      - install-component.md
      - uninstall-component.md
  - Back up and restore:
    - backup-restore-overview.md
    - backup-locks.md 
    - extended-mysqldump.md
    - start-transaction-with-consistent-snapshot.md
  - Secure:
    - LDAP features:
      - ldap-authentication.md
      - ldap-system-variables.md
    - Data masking:
      - data-masking-overview.md
      - install-data-masking-component.md
      - data-masking-function-list.md
      - uninstall-data-masking-component.md
    - pam-plugin.md
    - ssl-improvement.md
    - fido-authentication-plugin.md
    - encryption-functions.md
    - UUID_VX component:
      - uuid-versions.md
    
    - Data-at-rest-encryption:
      - data-at-rest-encryption.md
      - Keyring components:
        - keyring-components-plugins-overview.md
        - use-keyring-file.md
        - use-keyring-vault-component.md
        - using-kmip.md
        - using-amz-kms.md
        - encrypt-file-per-table-tablespace.md
        - encrypt-tablespaces.md
        - encrypt-system-tablespace.md
        - encrypt-doublewrite-file-pages.md
        - encrypt-temporary-files.md
        - encrypt-logs.md
        - rotate-master-key.md
        - verify-encryption.md     
  - Replicate:
    - group-replication-flow-control.md
    - group-replication-system-variables.md
    - Replication Security:
      - encrypt-binary-relay-log-files.md
  - Monitor:
    - jemalloc-profiling.md
    - user-stats.md
    - slow-extended.md
    - process-list.md
    - misc-info-schema-tables.md
  - Troubleshoot:
    - advisors.md
    - log-connection-error.md
    - innodb-corrupt-table-action.md
    - thread-based-profiling.md
    - stacktrace.md
    - libcoredumper.md
  - Storage engines:
    - Percona XtraDB storage engine:
      - percona-xtradb.md
      - improved-memory-engine.md
      - innodb-io.md
      - enforce-engine.md
      - innodb-show-status.md
      - show-engines.md
      - compressed-columns.md
      - innodb-fts-improvements.md
      - xtradb-performance-improvements.md
      - aio-page-requests.md
      - prefix-index-queries-optimization.md
      - query-limit-records.md
      - innodb-fragmentation-count.md
    - Percona MyRocks:
      - myrocks-index.md
      - install-myrocks.md
      - myrocks-added-features.md
      - myrocks-limitations.md
      - myrocks-differences.md
      - myrocks-information-schema-tables.md
      - myrocks-server-variables.md
      - myrocks-status-variables.md
      - myrocks-gap-locks-detection.md
      - myrocks-data-loading.md
  - Reference:
    - percona-server-system-variables.md
    - percona-server-versions-comparison.md
    - feature-comparison.md
    - server-version-numbers.md
    - development.md
    - telemetry.md
    - trademark-policy.md
    - index-info-schema-tables.md
    - faq.md
    - copyright-and-licensing-information.md
    - glossary.md
    - ai-docs.md
